### ISSUE TITLE
Improper `isStdlib()` path check using `strings.HasPrefix()`

### ISSUE THREAD

**Issue by jingyuanliang** [google/go-licenses#147] opened 2022-09-14 02:51 UTC
I have a setup where my `GOROOT` is `/usr/local/go` and source files are stored under `/usr/local/google`. go-licenses doesn't output anything in this case. I've traced it down and it's due to https://github.com/google/go-licenses/blob/13c8b648ff73469070f7f19c53dfbb88434370c4/licenses/library.go#L289 where `build.Default.GOROOT` got `/usr/local/go` and `pkg.GoFiles[0]` got `/usr/local/google/...` so it thinks everything is stdlib, then skips all of them.

**Comment by Bobgy** [comment] 2022-09-14 03:08
looks like we can just check prefix /usr/local/go/ instead

**Comment by Bobgy** [comment] 2022-09-14 03:09
Duplicate of https://github.com/google/go-licenses/issues/38

**Closed by Bobgy** 2022-09-14 03:09 UTC
